name: "manylinux2014_x86_64"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  setup-buildcache:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
