name: "Perf-Port Spack Buildcache"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  setup-buildcache:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup Spack
        uses: spack/setup-spack@v2

