name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run commands in Docker container
        uses: docker://quay.io/pypa/manylinux2014_x86_64
        with:
          entrypoint: /bin/bash
          args: |
            -c "
            echo 'This is a step before initializing the container'
            # Add more commands as needed before initializing the container

            echo 'This is another action before initializing the container'
            # Add more commands as needed before initializing the container

            # Now you are inside the container
            echo 'This step runs inside the container'
            # Add commands that need to run inside the container
            "
