name: "Test"

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
